NOOS-415/upgrade-python
noosenergy/noos-docker-images pull request #117
Opened 2023-09-11 09:36 UTC by zyassine

2023-09-18 12:27 UTC, pieeri requested changes
Quick question in relation to Dash version upgrade.

2023-09-18 12:27 UTC, pieeri commented on docker/jupyterlab/environment.yml
> +  - matplotlib
🐼 

To regroup under the "plotting" dependency category.

2023-09-18 12:27 UTC, pieeri commented on docker/circleci/Dockerfile
> +ARG PIPENV_RELEASE="2023.6.2"
🐼 

Would it be cleaner to squash such a commit into the previous one?

2023-09-18 12:27 UTC, pieeri commented on docker/jupyterlab/environment.yml
> +  - dash<2.10
❓ 

Is it required to include such a change with the upgrade towards Python `3.11.*` or could we ship Dash `2.*` into a subsequent PR (in conjonction with changes in `dash-neptune-mdc`)?

2023-09-18 12:27 UTC, pieeri commented on docker/circleci/Dockerfile
>  # # Provision Selenium (Firefox)
🐼 

Non-compliant comment formatting.

2023-09-18 12:44 UTC, zyassine commented on docker/jupyterlab/environment.yml
> +  - dash<2.10
I had an issue with pyyaml and pipenv. The solution I found is to upgrade pyyaml and I can't do it without Dash upgrade

2023-09-18 15:52 UTC, pieeri reviewed
LGTM

2023-09-21 08:28 UTC, pieeri approved these changes
Let's start rolling Python `3.11.*`!

2023-09-21 08:28 UTC, merged