Add templates extension to the hub
noosenergy/noos-docker-images pull request #126
Opened 2024-05-03 12:04 UTC by TheTimb

- Add jupyterlab_templates to environment.yml
- Fix some versions to ensure compatibility with jupyterlab<4
- Add jupyter_notebook_config.py file for templates extension configuration (modification of a directory name reflected in Dockerfile)
- Add fetchNews=false flag to remove jupyter news popup at startup in overrides.json

https://noosenergy.atlassian.net/browse/NOOS-721

2024-05-03 13:51 UTC, pieeri requested changes
🏓

2024-05-03 13:51 UTC, pieeri commented on docker/jupyterlab/Dockerfile
> +# Configure nbconvert & jupyterlab_templates
🐼 

Comment to be reworded maybe around the line "Configure Jupyterlab extensions" as per official docs:

https://jupyterlab.readthedocs.io/en/stable/user/directories.html#jupyterlab-user-settings-directory

2024-05-03 13:54 UTC, pieeri commented on docker/jupyterlab/config_extensions/jupyter_notebook_config.py
> +#c.JupyterLabTemplates.allowed_extensions = ["*.ipynb"]
🐼 

Annotated code to be removed if config isn't used

2024-05-06 06:49 UTC, chribag commented on docker/jupyterlab/lab/data/overrides.json
> +    "fetchNews": "false"
nice one !

2024-05-06 14:10 UTC, chribag requested changes

2024-05-06 14:10 UTC, chribag commented on docker/jupyterlab/config_extensions/jupyter_notebook_config.py
> +c = get_config()
This file should be similar in structure to the nbconvert one:

# Configuration file for jupyter-nbconvert.

# more info:
# https://nbconvert.readthedocs.io/en/latest/config_options.html
# https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/config.html


We could consider merging the 2 files, but I find having both like here much clearer indeed.

2024-05-06 15:34 UTC, chribag commented on docker/jupyterlab/config_extensions/jupyter_notebook_config.py
> +#------------------------------------------------------------------------------
🐼 format and wording not totally consistent with nbconvert file !

2024-05-06 15:35 UTC, chribag submitted a review, later dismissed

2024-05-07 09:23 UTC, pieeri requested changes
Thanks for the changes!

Could we piggybag such a PR to:

* upgrade the version of our CircleCI Orb to the latest one (v0.2.3)
https://circleci.com/developer/orbs/orb/noosenergy/noos-ci

* upgrade the terms of our open source license (2024)

2024-05-07 12:09 UTC, pieeri approved these changes
👍

2024-05-07 13:27 UTC, merged