NOOS-867/add-uv-python-package-manager-on-circleci-image
noosenergy/noos-docker-images pull request #129
Opened 2024-08-21 07:45 UTC by mthiboust

# Description

Add the `uv` python package manager to the CircleCI docker image.

**JIRA Reference**: [NOOS-867](https://noosenergy.atlassian.net/browse/NOOS-867)

2024-08-21 11:46 UTC, pieeri commented on docker/circleci/Dockerfile
> +    curl -LsSf https://astral.sh/uv/$UV_RELEASE/install.sh | sh
❓ 

Why not keeping it simple through a `pip` install? As long as the CircleCI base image is relying on `pyenv`, it would be best just to only rely on `uv` as Python package manager.

2024-08-21 14:33 UTC, mthiboust commented on docker/circleci/Dockerfile
> +    curl -LsSf https://astral.sh/uv/$UV_RELEASE/install.sh | sh
I thought it would be safer to isolate `uv` from any python environment, but we can indeed install it inside the existing python environment as per [the docs](https://docs.astral.sh/uv/getting-started/installation/#pypi). I'll update it in next commit.

_Note: I initially used `COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv` from the [docs about `uv` in docker](https://docs.astral.sh/uv/guides/integration/docker/), but I couldn't make the version dynamic because docker does not allow to use `ARG` inside the `COPY --from` clause (see [here](https://github.com/moby/moby/issues/34482))_

2024-08-21 21:36 UTC, pieeri requested changes
LGTM.

2024-08-21 21:36 UTC, pieeri commented on docker/circleci/Dockerfile
> +ENV PIPENV_VENV_IN_PROJECT=tre
🐼 

Typo on boolean.

2024-08-21 21:37 UTC, pieeri commented
@zyassine For a second pair of 👁️ !

2024-08-21 22:01 UTC, mthiboust commented on docker/circleci/Dockerfile
> +ENV PIPENV_VENV_IN_PROJECT=tre
Oops!

2024-08-22 11:58 UTC, zyassine approved these changes
LGTM !

2024-08-22 12:44 UTC, merged