Noos 881/reduce-jupyterlab-image-size (v2)
noosenergy/noos-docker-images pull request #131
Opened 2024-08-30 22:39 UTC by mthiboust

Follow-up on https://github.com/noosenergy/noos-docker-images/pull/130

# Description

Reduce the size of the jupyterlab image

**JIRA Reference**: [NOOS-881](https://noosenergy.atlassian.net/browse/NOOS-881)

# Changes

- [x] Switch to base-notebook:python-3.11.9 image (to avoid our previous issue with mamba bug in package resolution for `backports`)  and fix verson conflicts. We couldn't upgrade to `jupyterlab 4` because the `code-snippet` extension is only available for `jupyter < 4`
- [x] Install conda pacakges directly with the adequate permissions to speed up the `fix-permissions` script

2024-09-01 17:14 UTC, pieeri requested changes
@filiperosa @zyassine 

Something to think about with `dash-material-components`.

2024-09-01 17:14 UTC, pieeri commented on docker/jupyterlab/environment.yml
> -  - dash>=2,<2.10
⚠️ 

Dash has been pinned in `dash-material-components` ; not to rely on the `jupyter-dash` extension may require freeing up the constraint.

https://github.com/noosenergy/dash-material-components/blob/master/pyproject.toml#L43

2024-09-01 19:23 UTC, mthiboust commented on docker/jupyterlab/environment.yml
> -  - dash>=2,<2.10
Thanks, I didn't know this. I added back the constraint here to keep previous behavior.  

Current extension versions:
```bash
(base) jovyan@54ff594a46af:~$ jupyter labextension list
JupyterLab v3.6.8
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        nbdime-jupyterlab v2.2.0 enabled OK
        spreadsheet-editor v0.6.1 enabled OK (python, jupyterlab-spreadsheet-editor)
        jupyterlab-plotly v5.24.0 enabled OK
        jupyterlab_templates v0.4.1 enabled OK (python, jupyterlab_templates)
        jupyterlab-code-snippets v2.1.0 enabled OK (python, code_snippet)
        @jupyterlab/git v0.44.0 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v5.0.13 enabled OK (python, jupyterlab_widgets)
        @jupyterhub/jupyter-server-proxy v4.4.0 enabled OK

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        jupyterlab-dash v0.4.2 enabled OK


Uninstalled core extensions:
    @jupyterlab/extensionmanager-extension
```

2024-09-01 20:49 UTC, pieeri commented on docker/jupyterlab/environment.yml
> -  - dash>=2,<2.10
Thanks @mthiboust !

2024-09-01 20:49 UTC, pieeri approved these changes
🚢 !

2024-09-02 06:27 UTC, merged

2024-10-03 10:33 UTC, mthiboust commented on docker/jupyterlab/environment.yml
> -  - dash>=2,<2.10
@pieeri : FYI, we will update to a newer dash version because the `django-plotly-dash` project just released a new version compatible with `dash>=2.0,<3.0` just 2 days ago! See here: https://github.com/GibbsConsulting/django-plotly-dash/releases/tag/v2.4.0

cc @filiperosa @tommella90